apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jupyterlab
bases:
- ../../base
transformers:
- transformer-labels.yaml
- transformer-suffixprefix.yaml
images:
  - name: frontend-app01
    newName: abeyuki/jupyterlab-python-3.11.3-bullseye
    newTag: "1.0.0"
replicas:
- name: frontend-app01
  count: 1
patchesStrategicMerge:
- |-
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: frontend-app01
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: longhorn
    volumeMode: Filesystem
