apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod-jupyterlab
secretGenerator:
- name: docker-registry
  files:
   - '.dockerconfigjson=docker-registry.json'
  type: kubernetes.io/dockerconfigjson
bases:
- ../../base
transformers:
- transformer-labels.yaml
- transformer-suffixprefix.yaml
images:
  - name: frontend-app01
    newName: registry.gitlab.com/aimhighergg/docker-registry/jupyterlab
    newTag: "1.0"
replicas:
- name: frontend-app01
  count: 1
patchesStrategicMerge:
- |-
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: frontend-app01
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 1Gi
    storageClassName: longhorn
    volumeMode: Filesystem
- |-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app01
  labels:
    app.kubernetes.io/name: jupyterlab
spec:
  template:
    spec:
      imagePullSecrets:
        - name: docker-registry
      containers:
      - name: frontend-app01
        command: ["/bin/sh", "-c"]
        args:
        - |
          jupyter lab \
              --ip=0.0.0.0 \
              --allow-root \
              --no-browser \
              --NotebookApp.notebook_dir='/usr/src/app' \
              --NotebookApp.token=''
        volumeMounts:
        - name: jupyterlab
          mountPath: /usr/src/app
