apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jupyterlab
bases:
- ../../base
transformers:
- transformer-labels.yaml
- transformer-suffixprefix.yaml
images:
  - name: frontend-app01
    newName: jupyter/scipy-notebook
    newTag: "aarch64-ubuntu-22.04"
replicas:
- name: frontend-app01
  count: 1
patchesStrategicMerge:
- |-
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: frontend-app01
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 1Gi
    storageClassName: longhorn
    volumeMode: Filesystem
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: frontend-app01
    labels:
      app.kubernetes.io/name: jupyterlab
  spec:
    template:
      spec:
        imagePullSecrets:
          - name: docker-registry
        containers:
        - name: frontend-app01
          command: ["/bin/sh", "-c"]
          args:
          - |
            jupyter lab \
                --ip=0.0.0.0 \
                --allow-root \
                --no-browser \
                --NotebookApp.notebook_dir='/home/jovyan' \
                --NotebookApp.token="${JUPYTERLAB_TOKEN}"
          volumeMounts:
          - name: jupyterlab
            mountPath: /home/jovyan
