apiVersion: v1
kind: Service
metadata:
  name: frontend-app01
  labels:
    app.kubernetes.io: jupyterlab
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8888
  selector:
    app.kubernetes.io/name: jupyterlab
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontend-app01
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app01
  labels:
    app.kubernetes.io/name: jupyterlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jupyterlab
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jupyterlab
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - jupyterlab
            topologyKey: "kubernetes.io/hostname"
      imagePullSecrets:
        - name: docker-registry
      containers:
      - name: frontend-app01
        image: frontend-app01
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "0.25"
            memory: 245Mi
          limits:
            cpu: "0.5"
            memory: 526Mi
        command: ["/bin/sh", "-c"]
        args:
        - |
          jupyter lab \
              --ip=0.0.0.0 \
              --allow-root \
              --no-browser \
              --NotebookApp.notebook_dir='/home/JupyterLab/codes' \
              --NotebookApp.token=''
        env:
        - name: TZ
          value: Asia/Tokyo
        ports:
        - name: jupyterlab
          containerPort: 8888
        volumeMounts:
        - name: jupyterlab
          mountPath: /home/JupyterLab/codes
      volumes:
      - name: jupyterlab
        persistentVolumeClaim:
          claimName: frontend-app01
    